name: dask-expr
channels:
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - pytest-xdist
  - dask  # overridden by git tip below
  - pyarrow>=14.0.1
  - pandas>=2
  - pre-commit
  - xarray
  - pip:
      # TODO: Undo
      - git+https://github.com/jrbourbeau/distributed.git@numpy-124
      - git+https://github.com/jrbourbeau/dask.git@numpy-124
      # - git+https://github.com/dask/distributed
      # - git+https://github.com/dask/dask
