{% set major_minor_patch = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v').split('.') %}
{% set new_patch = major_minor_patch[2] | int + 1 %}
{% set version = (major_minor_patch[:2] + [new_patch]) | join('.') + environ.get('VERSION_SUFFIX', '') %}
{% set dask_version = environ.get('DASK_CORE_VERSION', '0.0.0.dev') %}


package:
  name: dask-expr
  version: {{ version }}

source:
  git_url: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  string: py_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - dask-core {{ dask_version }}
    - versioneer =0.28
    - tomli
  run:
    - python >=3.9
    - {{ pin_compatible('dask-core', max_pin='x.x.x.x') }}
    - pyarrow
    - pandas >=2

test:
  imports:
    - dask_expr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/dask-expr
  summary: 'High Level Expressions for Dask'
  description: |
    High Level Expressions for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/dask/dask-expr/blob/main/README.md
  dev_url: https://github.com/dask/dask-expr
